stages:
  - build
  - publish


build:
  stage: build
  only:
    - master
  tags:
    - pypi
  script:
    - python setup.py bdist_wheel
  artifacts:
    when: on_success
    paths:
      - dist/*


publish:
  stage: publish
  only:
    - master
  tags:
    - pypi
  script:
    - VERSION=$(python setup.py -V)
    - PKG=$(python setup.py --name)
    - pypi-private -v publish $PKG $VERSION
